### PR TITLE
Support Basler camera a2A2590-60umBAS (and other Basler cameras, untested)

### PR DESCRIPTION
**Pull request by antortjim**
This pull request provides the following corrections to the basler.py module:

* change the way pypylon is imported
* replace `Exposure` with `ExposureTime` as attribute in the Pylon camera object refering to the exposure time
* Set a default non-zero exposure time of 15000
* Define gain as kwarg of the Basler camera class with 0 as default
* Change timeout of framegrabber to something reasonable (100 instead of 1, maybe a smaller value is also ok, but 1 seems to not work for me)
* Change the way the device is selected. Instead of obtaining the list of available devices in the main thread and passing the selected one, obtain a list of device ids (0,... number of devices -1), obtain the devices in the camera process thread and select the device based on this index. Moreover, a default index of 0 is passed, to select the first device available if none is specified.

### CODE REVIEW

**Comment by antortjim** [comment]
This contribution is intended to solve #6

**Comment by antortjim** [comment]
For completeness, this request is tested with a2A2590-60umBAS on the following platform:

```
Ubuntu 20.04
Python 3.7.4 (in a conda environment)
conda 4.10.1
pypylon 6.1.1 (see installation instructions below)
opencv-python 4.5.1
dlclivegui with commit hash e4025172ce55c8ef640051462d110f8dc2ea2c6e
```

## To install pypylon:

1. I think Pylon Viewer needs to be installed. It can be downloaded for many platforms on the Basler website
2. Install swig (another dependency)
```
## Some dependencies I had to install on a fresh Ubuntu install
sudo apt install gcc g++
sudo apt install libpcre3-dev
sudo apt install make
# go to
# http://prdownloads.sourceforge.net/swig/swig-4.0.2.tar.gz
# and download the tar gz
tar -zxvf swig-4.0.2.tar.gz
cd swig-4.0.2
./configure
make
sudo make install
```
3. Instal pypylon
```
wget https://github.com/basler/pypylon/archive/refs/tags/1.7.2.tar.gz
tar -zxvf 1.7.2.tar.gz
cd pypylon-1.7.2
python setup.py install
# this installs pypylon version 6.1.1
```

**Comment by MMathisLab** [comment]
@antortjim thanks so much for this. Could I make the suggestion that your additional installation instructions (https://github.com/DeepLabCut/DeepLabCut-live-GUI/pull/11#issuecomment-848103129) go in a new section. I opened a PR on your branch, thanks!

**Comment by antortjim** [comment]
Dear @MMathisLab thanks for considering the PR! :) I have extended the documentation I wrote on the PR comments and put it in the file you suggested.

**Review by MMathisLab — APPROVED** [review]

**Review by MMathisLab — APPROVED** [review]

**Pull request merged**
